### PR TITLE
Adding support for controlling gallery/speaker view

### PR DESCRIPTION
**Pull request by statik**
Related to #5, I have added support for toggling between Gallery and Speaker view, it should work on both macOS and Windows.

I would welcome any feedback on the implementation. I have done some testing on my macOS laptop and it seems to work, and I have tested the getZoomStatus.py tool on Windows and it works.

### CODE REVIEW

**Comment by statik** [comment]
I fixed the creation of the local installer directory, and managed to get the plugin loaded. Testing on macOS with zoom 5.3.0, the toggle view button is not causing zoom to change views, even though manually typing command+shift+w does toggle the gallery/speaker view.

**Comment by statik** [comment]
Testing this in script editor works as expected to toggle the speaker/gallery view for zoom
```
tell application "zoom.us"
	tell application "System Events" to tell application process "zoom.us"
		keystroke "w" using {shift down, command down}
	end tell
end tell
```

**Comment by statik** [comment]
I found the bug with the mac toggle of speaker/gallery view, last 2 bits are fixing up the icons and doing the osascript for detecting the speaker/gallery view state.

**Comment by statik** [comment]
A build for macOS testing is available here: https://github.com/kindlyops/streamdeck-zoom-plugin/releases/tag/v1.1

**Comment by smitmartijn** [comment]
Hi Elliot,

Apologies for the delay, but there was a lot in-flux with the code structure. The Windows support needed an overhaul and I started using the menu on macOS to trigger actions. Can you refactor this code to fit the current structure? thanks!

**Comment by statik** [comment]
Sure thing! I'll refactor this.

**Comment by statik** [comment]
@smitmartijn I took a pass at refactoring, still need to do some testing. How does it look?
BTW, I am pretty new to using CMake. How do you typically build this for testing?

**Comment by statik** [comment]
I managed to get this built and tested on Windows, the toggle gallery view is not working. I believe the UI element layout is different enough for the Speaker View and Gallery View menu items that the code is not finding them. I need to do more research to find out how to find these items in the tree. I am attaching a screenshot of the menu item.
Zoom gallery view menu

**Comment by smitmartijn** [comment]
Thanks, @statik - looks good so far. Are you saying the detection of the type view isn't working, or the button to toggle the view isn't working?

**Comment by statik** [comment]
@smitmartijn thanks for looking things over!
Sending the keys to toggle the view is working, but I haven't been able to work out the code to detect the current view. The current code does find the button in the Meeting window named "View". But, I haven't figured out how to navigate down further and inspect the menu that shows when the view button is clicked to read out the current view state. I do need the current view state because there is a different shortcut for going to gallery view and going to speaker view. Now that I wrote that out I guess a different approach would be to provide two streamdeck buttons, one for gallery and one for speaker, rather than trying to get a toggle view on a single button. What do you think, is it possible to detect the current view or should I switch to doing two buttons?
zoom gallery view button

**Comment by statik** [comment]
I'm going to close this as I won't have time to dig deeper into the Windows API. Anyone else is welcome to pick up this code if it is useful.

**Pull request closed without merging**
